name: pids_framework
channels:
  - pytorch
  - conda-forge
  - dglteam
  - defaults

dependencies:
  - python=3.10
  - pip
  
  # PyTorch with CUDA support
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6
  
  # Scientific Computing
  - numpy=1.23.5
  - scipy=1.10.1
  - pandas=1.5.3
  - scikit-learn=1.2.2
  
  # Graph Libraries
  - networkx=2.8.8
  - graphviz=0.20.1
  
  # Utilities
  - tqdm
  - pyyaml
  - joblib
  - psutil
  
  # Visualization
  - matplotlib=3.7.1
  - seaborn=0.12.2
  
  # Database
  - psycopg2=2.9.6
  - sqlalchemy=2.0.15
  
  # Development
  - pytest
  - black
  - flake8
  - isort
  
  # Pip dependencies
  - pip:
      - dgl==1.0.0
      - torch-geometric==2.1.0
      - torch-scatter==2.0.9
      - torch-sparse==0.6.15
      - torch-cluster==1.6.0
      - xxhash==3.2.0
      - wandb==0.15.0
      - tensorboard==2.13.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - plotly==5.14.1
      - fastapi==0.95.2
      - uvicorn==0.22.0
      - flask==2.3.2
      - python-louvain==0.16
