# MAGIC Model Configuration
# Masked Graph Autoencoder for Provenance-based Intrusion Detection
# Paper: USENIX Security 2024

model_name: magic
model_type: autoencoder

# Model Architecture
architecture:
  # Encoder configuration
  encoder:
    type: gat                # Graph Attention Network
    in_dim: 128              # Node feature dimension (n_dim)
    hidden_dim: 256          # Hidden dimension size (num_hidden)
    out_dim: 256             # Output embedding dimension
    num_layers: 4            # Number of GNN layers
    num_heads: 4             # Number of attention heads
    dropout: 0.1
    activation: prelu        # Activation function
    use_edge_attr: true
    
  # Decoder configuration (for autoencoder reconstruction)
  decoder:
    type: reconstruction     # Reconstruction decoder for autoencoder
    in_dim: 256              # Input from encoder
    hidden_dim: 256
    out_dim: 128             # Reconstruct node features
    mask_rate: 0.3           # Masking rate for autoencoder (30%)
    activation: prelu
    norm: batchnorm          # Normalization layer

# Training
training:
  learning_rate: 0.0005
  weight_decay: 0.0
  num_epochs: 500
  batch_size: 1            # Process whole graph at once
  optimizer: adam
  scheduler: null          # No learning rate scheduling
  
  # Early stopping
  patience: 50
  min_delta: 0.001
  
  # Loss weights
  loss_weights:
    reconstruction: 1.0
    
# Evaluation
evaluation:
  k_neighbors: 20          # For k-NN anomaly detection
  distance_metric: cosine  # Distance metric for k-NN
  threshold_percentile: 95 # Anomaly threshold
  
# Dataset-specific settings
dataset:
  name: streamspot         # streamspot, darpa, custom
  num_classes: 2           # Binary classification
  
# Device
device: cuda              # cuda or cpu
seed: 42

# Checkpointing
checkpoint:
  save_dir: checkpoints/magic
  save_interval: 10        # Save every N epochs
  keep_best_only: true
  metric: auroc           # Metric to monitor
  mode: max               # Maximize AUROC
