# Orthrus Model Configuration
# Multi-Decoder Provenance Learning with Contrastive Learning
# Paper: USENIX Security 2025

model_name: orthrus
model_type: multi_decoder

# Model Architecture
architecture:
  # Encoder configuration
  encoder:
    type: gat                # Graph Attention Network (encoder_type)
    in_dim: 100              # Input feature dimension
    hidden_dim: 128          # Hidden dimension
    out_dim: 100             # Output embedding dimension
    num_layers: 3            # Number of layers (encoder_layers)
    num_heads: 4             # Number of attention heads (encoder_heads)
    dropout: 0.1             # Dropout rate (encoder_dropout)
    activation: relu
    use_edge_attr: true      # Use edge attributes
    
  # Multi-decoder configuration
  decoders:
    # Primary decoder - edge anomaly detection
    primary:
      type: edge             # Edge-level predictions
      in_dim: 100
      hidden_dim: 128        # decoder_hidden_dim
      out_dim: 2             # Binary classification
      activation: relu
      
    # Contrastive decoder
    contrastive:
      type: contrastive      # Contrastive learning
      in_dim: 100
      hidden_dim: 128
      out_dim: 100
      temperature: 0.07      # Temperature for contrastive loss
      
    # Reconstruction decoder (auxiliary)
    reconstruction:
      type: reconstruction   # Graph reconstruction
      in_dim: 100
      hidden_dim: 128
      out_dim: 100
      
  # Node/Edge metadata
  num_nodes: 100000          # Expected number of nodes
  num_edge_types: 10         # Number of different edge types
  
# Training
training:
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 200
  batch_size: 4            # Number of graphs per batch
  optimizer: adam
  scheduler:
    type: cosine
    T_max: 200
    eta_min: 0.00001
  
  # Early stopping
  patience: 30
  min_delta: 0.0005
  
  # Loss weights (for multi-task learning)
  loss_weights:
    decoder_1: 1.0
    decoder_2: 1.0
    decoder_3: 1.0
    contrastive: 0.5
    
  # Gradient clipping
  grad_clip: 1.0
  
# Evaluation
evaluation:
  eval_interval: 10
  metrics:
    - auroc
    - auprc
    - f1_score
    - precision
    - recall
  
  # Anomaly detection
  anomaly_threshold_method: percentile  # percentile or adaptive
  threshold_percentile: 95
    
# Dataset-specific settings
dataset:
  name: darpa             # darpa, streamspot, custom
  num_classes: 2
  preprocess:
    normalize_features: true
    add_self_loops: true
  
# Device
device: cuda
seed: 42

# Checkpointing
checkpoint:
  save_dir: checkpoints/orthrus
  save_interval: 10
  keep_best_only: true
  metric: auroc
  mode: max
  
# Database configuration (for Orthrus original implementation)
database:
  use_database: false      # Set to true if using PostgreSQL backend
  host: localhost
  port: 5432
  dbname: orthrus
  user: postgres
  password: null
